const provinces = [
  {
    name: "Hà Nội",
    districts: [
      "Ba Đình",
      "Hoàn Kiếm",
      "Tây Hồ",
      "Long Biên",
      "Cầu Giấy",
      "Đống Đa",
      "Hai Bà Trưng",
      "Hoàng Mai",
      "Thanh Xuân",
      "Sóc Sơn",
      "Đông Anh",
      "Gia Lâm",
      "Nam Từ Liêm",
      "Thanh Trì",
      "Bắc Từ Liêm",
      "Mê Linh",
      "Hà Đông",
      "Sơn Tây",
      "Ba Vì",
      "Phúc Thọ",
      "Đan Phượng",
      "Hoài Đức",
      "Quốc Oai",
      "Thạch Thất",
      "Chương Mỹ",
      "Thanh Oai",
      "Thường Tín",
      "Phú Xuyên",
      "Ứng Hòa",
      "Mỹ Đức",
    ],
  },
  {
    name: "Hồ Chí Minh",
    districts: [
      "Quận 1",
      "Quận 2",
      "Quận 3",
      "Quận 4",
      "Quận 5",
      "Quận 6",
      "Quận 7",
      "Quận 8",
      "Quận 9",
      "Quận 10",
      "Quận 11",
      "Quận 12",
      "Bình Tân",
      "Bình Thạnh",
      "Gò Vấp",
      "Phú Nhuận",
      "Tân Bình",
      "Tân Phú",
      "Thủ Đức",
      "Bình Chánh",
      "Cần Giờ",
      "Củ Chi",
      "Hóc Môn",
      "Nhà Bè",
    ],
  },
  {
    name: "Hải Phòng",
    districts: [
      "Hồng Bàng",
      "Ngô Quyền",
      "Lê Chân",
      "Hải An",
      "Kiến An",
      "Đồ Sơn",
      "Dương Kinh",
      "Thuỷ Nguyên",
      "An Dương",
      "An Lão",
      "Kiến Thuỵ",
      "Tiên Lãng",
      "Vĩnh Bảo",
      "Cát Hải",
      "Bạch Long Vĩ",
    ],
  },
  {
    name: "Đà Nẵng",
    districts: [
      "Hải Châu",
      "Thanh Khê",
      "Sơn Trà",
      "Ngũ Hành Sơn",
      "Liên Chiểu",
      "Cẩm Lệ",
      "Hòa Vang",
      "Hoàng Sa",
    ],
  },
  {
    name: "Cần Thơ",
    districts: [
      "Ninh Kiều",
      "Bình Thủy",
      "Cái Răng",
      "Ô Môn",
      "Thốt Nốt",
      "Vĩnh Thạnh",
      "Cờ Đỏ",
      "Phong Điền",
      "Thới Lai",
    ],
  },
  // ... Thêm các tỉnh/thành còn lại với các quận/huyện tiêu biểu ...
  {
    name: "An Giang",
    districts: [
      "Long Xuyên",
      "Châu Đốc",
      "An Phú",
      "Tân Châu",
      "Phú Tân",
      "Châu Phú",
      "Tịnh Biên",
      "Tri Tôn",
      "Châu Thành",
      "Chợ Mới",
      "Thoại Sơn",
    ],
  },
  {
    name: "Bà Rịa - Vũng Tàu",
    districts: [
      "Vũng Tàu",
      "Bà Rịa",
      "Châu Đức",
      "Xuyên Mộc",
      "Long Điền",
      "Đất Đỏ",
      "Tân Thành",
      "Côn Đảo",
    ],
  },
  {
    name: "Bắc Giang",
    districts: [
      "Thành phố Bắc Giang",
      "Huyện Hiệp Hòa",
      "Huyện Lạng Giang",
      "Huyện Lục Nam",
      "Huyện Lục Ngạn",
      "Huyện Sơn Động",
      "Huyện Tân Yên",
      "Huyện Việt Yên",
      "Huyện Yên Dũng",
      "Huyện Yên Thế",
    ],
  },
  {
    name: "Bắc Kạn",
    districts: [
      "Thành phố Bắc Kạn",
      "Huyện Ba Bể",
      "Huyện Bạch Thông",
      "Huyện Chợ Đồn",
      "Huyện Chợ Mới",
      "Huyện Na Rì",
      "Huyện Ngân Sơn",
      "Huyện Pác Nặm",
    ],
  },
  {
    name: "Bạc Liêu",
    districts: [
      "Thành phố Bạc Liêu",
      "Thị xã Giá Rai",
      "Huyện Đông Hải",
      "Huyện Hòa Bình",
      "Huyện Hồng Dân",
      "Huyện Phước Long",
      "Huyện Vĩnh Lợi",
    ],
  },
  {
    name: "Bắc Ninh",
    districts: [
      "Thành phố Bắc Ninh",
      "Thành phố Từ Sơn",
      "Huyện Gia Bình",
      "Huyện Lương Tài",
      "Huyện Quế Võ",
      "Huyện Thuận Thành",
      "Huyện Tiên Du",
      "Huyện Yên Phong",
    ],
  },
  {
    name: "Bến Tre",
    districts: [
      "Thành phố Bến Tre",
      "Huyện Ba Tri",
      "Huyện Bình Đại",
      "Huyện Châu Thành",
      "Huyện Chợ Lách",
      "Huyện Giồng Trôm",
      "Huyện Mỏ Cày Bắc",
      "Huyện Mỏ Cày Nam",
      "Huyện Thạnh Phú",
    ],
  },
  {
    name: "Bình Định",
    districts: [
      "Thành phố Quy Nhơn",
      "Thị xã An Nhơn",
      "Thị xã Hoài Nhơn",
      "Huyện An Lão",
      "Huyện Hoài Ân",
      "Huyện Phù Cát",
      "Huyện Phù Mỹ",
      "Huyện Tây Sơn",
      "Huyện Tuy Phước",
      "Huyện Vân Canh",
      "Huyện Vĩnh Thạnh",
    ],
  },
  {
    name: "Bình Dương",
    districts: [
      "Thành phố Thủ Dầu Một",
      "Thành phố Dĩ An",
      "Thành phố Thuận An",
      "Thị xã Bến Cát",
      "Thị xã Tân Uyên",
      "Huyện Bàu Bàng",
      "Huyện Bắc Tân Uyên",
      "Huyện Dầu Tiếng",
      "Huyện Phú Giáo",
    ],
  },
  {
    name: "Bình Phước",
    districts: [
      "Thành phố Đồng Xoài",
      "Thị xã Bình Long",
      "Thị xã Chơn Thành",
      "Thị xã Phước Long",
      "Huyện Bù Đăng",
      "Huyện Bù Đốp",
      "Huyện Bù Gia Mập",
      "Huyện Đồng Phú",
      "Huyện Hớn Quản",
      "Huyện Lộc Ninh",
      "Huyện Phú Riềng",
    ],
  },
  {
    name: "Bình Thuận",
    districts: [
      "Thành phố Phan Thiết",
      "Thị xã La Gi",
      "Huyện Bắc Bình",
      "Huyện Đức Linh",
      "Huyện Hàm Tân",
      "Huyện Hàm Thuận Bắc",
      "Huyện Hàm Thuận Nam",
      "Huyện Phú Quý",
      "Huyện Tánh Linh",
      "Huyện Tuy Phong",
    ],
  },
  {
    name: "Cà Mau",
    districts: [
      "Thành phố Cà Mau",
      "Huyện Cái Nước",
      "Huyện Đầm Dơi",
      "Huyện Năm Căn",
      "Huyện Ngọc Hiển",
      "Huyện Phú Tân",
      "Huyện Thới Bình",
      "Huyện Trần Văn Thời",
      "Huyện U Minh",
    ],
  },
  {
    name: "Cao Bằng",
    districts: [
      "Thành phố Cao Bằng",
      "Huyện Bảo Lạc",
      "Huyện Bảo Lâm",
      "Huyện Hạ Lang",
      "Huyện Hà Quảng",
      "Huyện Hòa An",
      "Huyện Nguyên Bình",
      "Huyện Phục Hòa",
      "Huyện Quảng Hòa",
      "Huyện Thạch An",
      "Huyện Trùng Khánh",
    ],
  },
  {
    name: "Đắk Lắk",
    districts: [
      "Thành phố Buôn Ma Thuột",
      "Thị xã Buôn Hồ",
      "Huyện Buôn Đôn",
      "Huyện Cư Kuin",
      "Huyện Cư M'gar",
      "Huyện Ea H'leo",
      "Huyện Ea Kar",
      "Huyện Ea Súp",
      "Huyện Krông Ana",
      "Huyện Krông Bông",
      "Huyện Krông Buk",
      "Huyện Krông Năng",
      "Huyện Krông Pắc",
      "Huyện Lắk",
      "Huyện M'Drắk",
    ],
  },
  {
    name: "Đắk Nông",
    districts: [
      "Thành phố Gia Nghĩa",
      "Huyện Cư Jút",
      "Huyện Đắk Glong",
      "Huyện Đắk Mil",
      "Huyện Đắk R'Lấp",
      "Huyện Đắk Song",
      "Huyện Krông Nô",
      "Huyện Tuy Đức",
    ],
  },
  {
    name: "Điện Biên",
    districts: [
      "Thành phố Điện Biên Phủ",
      "Thị xã Mường Lay",
      "Huyện Điện Biên",
      "Huyện Điện Biên Đông",
      "Huyện Mường Ảng",
      "Huyện Mường Chà",
      "Huyện Mường Nhé",
      "Huyện Nậm Pồ",
      "Huyện Tủa Chùa",
      "Huyện Tuần Giáo",
    ],
  },
  {
    name: "Đồng Nai",
    districts: [
      "Thành phố Biên Hòa",
      "Thành phố Long Khánh",
      "Huyện Cẩm Mỹ",
      "Huyện Định Quán",
      "Huyện Long Thành",
      "Huyện Nhơn Trạch",
      "Huyện Tân Phú",
      "Huyện Thống Nhất",
      "Huyện Trảng Bom",
      "Huyện Vĩnh Cửu",
      "Huyện Xuân Lộc",
    ],
  },
  {
    name: "Đồng Tháp",
    districts: [
      "Thành phố Cao Lãnh",
      "Thành phố Hồng Ngự",
      "Thành phố Sa Đéc",
      "Huyện Cao Lãnh",
      "Huyện Châu Thành",
      "Huyện Hồng Ngự",
      "Huyện Lai Vung",
      "Huyện Lấp Vò",
      "Huyện Tam Nông",
      "Huyện Tân Hồng",
      "Huyện Thanh Bình",
      "Huyện Tháp Mười",
    ],
  },
  {
    name: "Gia Lai",
    districts: [
      "Thành phố Pleiku",
      "Thị xã An Khê",
      "Thị xã Ayun Pa",
      "Huyện Chư Păh",
      "Huyện Chư Prông",
      "Huyện Chư Pưh",
      "Huyện Chư Sê",
      "Huyện Đắk Đoa",
      "Huyện Đắk Pơ",
      "Huyện Đức Cơ",
      "Huyện Ia Grai",
      "Huyện Ia Pa",
      "Huyện Kbang",
      "Huyện Kông Chro",
      "Huyện Krông Pa",
      "Huyện Mang Yang",
      "Huyện Phú Thiện",
    ],
  },
  {
    name: "Hà Giang",
    districts: [
      "Thành phố Hà Giang",
      "Huyện Bắc Mê",
      "Huyện Bắc Quang",
      "Huyện Đồng Văn",
      "Huyện Hoàng Su Phì",
      "Huyện Mèo Vạc",
      "Huyện Quản Bạ",
      "Huyện Quang Bình",
      "Huyện Vị Xuyên",
      "Huyện Xín Mần",
      "Huyện Yên Minh",
    ],
  },
  {
    name: "Hà Nam",
    districts: [
      "Thành phố Phủ Lý",
      "Thị xã Duy Tiên",
      "Huyện Bình Lục",
      "Huyện Kim Bảng",
      "Huyện Lý Nhân",
      "Huyện Thanh Liêm",
    ],
  },
  {
    name: "Hà Tĩnh",
    districts: [
      "Thành phố Hà Tĩnh",
      "Thị xã Hồng Lĩnh",
      "Thị xã Kỳ Anh",
      "Huyện Cẩm Xuyên",
      "Huyện Can Lộc",
      "Huyện Đức Thọ",
      "Huyện Hương Khê",
      "Huyện Hương Sơn",
      "Huyện Kỳ Anh",
      "Huyện Lộc Hà",
      "Huyện Nghi Xuân",
      "Huyện Thạch Hà",
      "Huyện Vũ Quang",
    ],
  },
];

export default provinces;
